import { Seconds } from ".";

export default {
  title: "Components/Seconds",
  component: Seconds,
  argTypes: {
    seconds: {
      options: [
        "second-01",
        "second-29",
        "second-19",
        "second-17",
        "second-10",
        "second-43",
        "second-26",
        "second-50",
        "second-11",
        "second-37",
        "second-15",
        "second-21",
        "second-03",
        "default",
        "second-55",
        "second-47",
        "second-39",
        "second-30",
        "second-09",
        "second-04",
        "second-02",
        "second-13",
        "second-40",
        "second-53",
        "second-18",
        "second-51",
        "second-23",
        "second-22",
        "second-44",
        "second-52",
        "second-08",
        "second-38",
        "second-06",
        "second-07",
        "second-48",
        "second-25",
        "second-28",
        "second-57",
        "second-20",
        "second-49",
        "second-24",
        "second-27",
        "second-32",
        "second-33",
        "second-42",
        "second-45",
        "second-36",
        "second-54",
        "second-31",
        "seconds-59",
        "second-14",
        "second-56",
        "second-46",
        "second-35",
        "second-05",
        "second-34",
        "second-16",
        "second-12",
        "second-41",
      ],
      control: { type: "select" },
    },
  },
};

export const Default = {
  args: {
    seconds: "second-01",
  },
};
